### PR TITLE
Fix IABEssenceClipWrappedElement key

### LINKED ISSUE #59: IMF_IABEssenceClipWrappedElement UL value is incorrect in written IMF MXF files.
The value of IMF_IABEssenceClipWrappedElement UL should be 060e2b34.01020101.0d010301.16**01**0d**01** after it is written to the MXF file. 

The value ends up being 060e2b34.01020101.0d010301.16**7f**0d**7f**

### PR DESCRIPTION
**Pull request by palemieux**
Closes #59

### CODE REVIEW

File: src/AS_02_IAB.cpp [hunk 1]
```diff
@@ -179,7 +183,7 @@ AS_02::IAB::MXFWriter::OpenWrite(
 
     byte_t clip_buffer[RESERVED_KL_SIZE] = { 0 };
 
-    memcpy(clip_buffer, this->m_Writer->m_Dict->ul(MDD_IMF_IABEssenceClipWrappedElement), ASDCP::SMPTE_UL_LENGTH);
+    memcpy(clip_buffer, element_ul_bytes, ASDCP::SMPTE_UL_LENGTH);
```
Comment (kblinova) [inline src/AS_02_IAB.cpp:186]: Why not define MDD_IMF_IABEssenceClipWrappedElement to include 01 and 01 in places of 7f and 7f? This Essence UL is defined to be in this context of OP1 header. What flexibility does defining this UL as 7f and 7f add?

Comment (palemieux) [reply src/AS_02_IAB.cpp:186]: > What flexibility does defining this UL as 7f and 7f add?

The UL matches the [SMPTE registers](https://registry.smpte-ra.org/view/development/Essence.xml) exactly.

Comment (kblinova) [reply src/AS_02_IAB.cpp:186]: A couple of things:
- It would be good to have a way to set these bytes in ULs in a systematic way instead of using array subscripts; That makes is a supported library functionality
- There will be an issue comparing the UL found in the MXF files back with the MDD table definitions. This happens in as-02-info and klv-walk where the ULs are turned into printable strings for human consumption.

Comment (jhursty) [reply src/AS_02_IAB.cpp:186]: Following this expedient pull request I would appreciate a contribution that better addresses the 7f placeholder issues. What constitutes "better" is not yet obvious to me.

Comment (palemieux) [reply src/AS_02_IAB.cpp:186]: @jhursty @kblinova Opened https://github.com/cinecert/asdcplib/issues/67
